### ISSUE TITLE
[Tracker] Godot feature parity 

### ISSUE THREAD

**Issue by Demindiro** [Demindiro/godot_rapier3d#4]
This issue is to keep track of what features are still missing to achieve full compatibility with Godot.

# Area

Fully implemented

# Body

- [ ] Contact events
- [ ] Ray pickable: it simply prevents the body from being detected by rays
- [ ] Continuous Collision Detection (CCD)
- [ ] Axis locking

### Won't be implemented
- **Margins**: they are not relevant in Rapier.
- **32 bit collisions groups**: 16 bits ought to be enough for the vast majority of usecases (if not, I'd like to know)

# Joints

- [ ] 6DOF joint (**requires `FreeJoint` to be implemented upstream**)
- [ ] Cone twist joint (not sure what exactly it's supposed to do, but it sounds like a `BallJoint` with limits)
- [ ] Pin joint (`FixedJoint`)
- [ ] Slider joint (can be **partially** implemented with `PrismaticJoint`, but requires `PinslotJoint` for rotations)
- [ ] Solver priority (is it even relevant?)

# Soft bodies

Soft bodies can't be implemented as they don't exist. It doesn't seem like they will be implemented soon either (no roadmap).

# Spaces

## Direct space state
- [ ] `cast_motion`
- [ ] `get_rest_info`
- [ ] `intersect_shape`

**Comment by ValorZard** [comment]
So, would someone be able to use a KinematicCharacter with godot rapier and be able to use it without  issue?

**Comment by Demindiro** [comment]
Currently not, as Rapier doesn't have a built-in character controller and this project doesn't provide one yet either. Someone on the Dimforge Discord is (was?) working on one, though I don't know what the status is.

**Comment by ValorZard** [comment]
So if I wanted to make a game using this, what would I have to do then?

**Comment by Demindiro** [comment]
I'd ask on the Dimforge Discord about the character controller. Maybe it can be integrated into this project.

If not, something will have to be created from scratch.

**Comment by ValorZard** [comment]
After checking back, there isnt a character controller, but people have offered to give advice. There will need to be a custom one built
